"""add represent_image ti trip_days

Revision ID: 7980b42b0eb9
Revises: 61a0e7f2140a
Create Date: 2026-05-21 09:39:01.939823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7980b42b0eb9'
down_revision: Union[str, Sequence[str], None] = '61a0e7f2140a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_days', sa.Column('represent_image', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_days', 'represent_image')
    # ### end Alembic commands ###
