"""merge diaries into trip_days

trip_days 와 diaries 는 1:1 관계라 한 테이블로 합친다.
diaries 의 내용 컬럼(content, symbol, word_count, generated_at)을 trip_days 로 옮기고,
diaries 테이블은 제거한다. (title 은 trips.title 과 중복이라 버림, user_id 는 trips 에서 파생)
생성 이력 테이블 diary_generations 는 그대로 두되, 연결을 diary_id → trip_day_id 로 바꾼다.

API 응답(DayPage)·프론트는 이미 day+diary 를 한 덩어리로 다루므로 변경 없음.

upgrade()   = 합치기,  downgrade() = 다시 분리(원복). downgrade 로 언제든 이전 구조 복귀 가능.

Revision ID: a7d2f4b8c1e9
Revises: f3a9c1d4b2e6
Create Date: 2026-05-24

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a7d2f4b8c1e9"
down_revision: Union[str, Sequence[str], None] = "f3a9c1d4b2e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) trip_days 에 일기 내용 컬럼 4개 추가 (생성 전엔 비어 있을 수 있어 nullable)
    op.add_column("trip_days", sa.Column("content", sa.Text(), nullable=True))
    op.add_column("trip_days", sa.Column("symbol", sa.String(length=50), nullable=True))
    op.add_column("trip_days", sa.Column("word_count", sa.Integer(), nullable=True))
    op.add_column("trip_days", sa.Column("generated_at", sa.DateTime(), nullable=True))

    # 2) diaries 의 내용을 trip_days 로 복사 (같은 날끼리 trip_day_id 로 매칭)
    op.execute(
        """
        UPDATE trip_days AS t
        SET content = d.content,
            symbol = d.symbol,
            word_count = d.word_count,
            generated_at = d.generated_at
        FROM diaries AS d
        WHERE d.trip_day_id = t.id
        """
    )

    # 3) diary_generations 의 연결을 diary_id → trip_day_id 로 변경
    op.add_column(
        "diary_generations", sa.Column("trip_day_id", sa.BigInteger(), nullable=True)
    )
    op.execute(
        """
        UPDATE diary_generations AS g
        SET trip_day_id = d.trip_day_id
        FROM diaries AS d
        WHERE g.diary_id = d.id
        """
    )
    op.drop_column("diary_generations", "diary_id")

    # 4) 이제 비어버린 diaries 테이블 제거
    op.drop_table("diaries")


def downgrade() -> None:
    # 1) diaries 테이블 다시 생성 (baseline 과 동일 구조 + id 자동증가)
    op.create_table(
        "diaries",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("trip_day_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.Column("symbol", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("ALTER TABLE diaries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")

    # 2) trip_days 의 일기 내용을 diaries 로 되돌림 (날마다 1개씩 복원)
    #    title 은 trips.title 에서, user_id 도 trips 에서 가져옴(합칠 때 버렸던 값 복원)
    op.execute(
        """
        INSERT INTO diaries
            (trip_day_id, user_id, title, content, word_count, generated_at, symbol, created_at, updated_at)
        SELECT t.id, tr.user_id, tr.title, COALESCE(t.content, ''),
               t.word_count, t.generated_at, t.symbol, t.created_at, CURRENT_TIMESTAMP
        FROM trip_days AS t
        JOIN trips AS tr ON tr.id = t.trip_id
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('diaries', 'id'),
            GREATEST((SELECT COALESCE(MAX(id), 0) FROM diaries), 1),
            (SELECT COUNT(*) > 0 FROM diaries)
        )
        """
    )

    # 3) diary_generations 연결을 trip_day_id → diary_id 로 복원
    op.add_column(
        "diary_generations", sa.Column("diary_id", sa.BigInteger(), nullable=True)
    )
    op.execute(
        """
        UPDATE diary_generations AS g
        SET diary_id = d.id
        FROM diaries AS d
        WHERE d.trip_day_id = g.trip_day_id
        """
    )
    op.drop_column("diary_generations", "trip_day_id")

    # 4) trip_days 에서 일기 컬럼 제거
    op.drop_column("trip_days", "generated_at")
    op.drop_column("trip_days", "word_count")
    op.drop_column("trip_days", "symbol")
    op.drop_column("trip_days", "content")
