"""add travel_style_analysis and trip flag

Revision ID: d566d1945789
Revises: a7d2f4b8c1e9
Create Date: 2026-05-28 16:16:29.488514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd566d1945789'
down_revision: Union[str, Sequence[str], None] = 'a7d2f4b8c1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diary_generations', 'trip_day_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_foreign_key(None, 'photos', 'trip_days', ['trip_day_id'], ['id'])
    op.alter_column('trip_days', 'symbol',
               existing_type=sa.VARCHAR(length=50),
               comment='Twemoji codepoint (lowercase hex, multi-codepoint joined by -). e.g. 1f60a, 1f1f0-1f1f7',
               existing_nullable=True)
    op.add_column('trips', sa.Column('flag', sa.String(length=50), nullable=True, comment="Twemoji codepoint for the trip's representative flag emoji. Multi-codepoint joined by '-', e.g. 1f1f0-1f1f7"))
    op.add_column('users', sa.Column('travel_style_analysis', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'travel_style_analysis')
    op.drop_column('trips', 'flag')
    op.alter_column('trip_days', 'symbol',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Twemoji codepoint (lowercase hex, multi-codepoint joined by -). e.g. 1f60a, 1f1f0-1f1f7',
               existing_nullable=True)
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.alter_column('diary_generations', 'trip_day_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
