"""add identity(자동증가) to all id columns

기존 스키마는 모든 PK id가 평범한 BigInteger(자동증가 없음)였다.
그래서 시드처럼 id를 직접 박는 INSERT만 가능하고, 앱에서 id 없이 INSERT하면
"null value in column id" 에러가 났다. 모든 테이블 id에 IDENTITY를 추가하고,
기존 데이터와 안 겹치게 시퀀스를 현재 max(id) 다음으로 맞춘다.

GENERATED BY DEFAULT AS IDENTITY → 자동 생성하되, 필요하면 id를 직접 지정하는 것도 허용
(시드/이관 호환). 기존 데이터·쿼리에는 영향 없는 추가 변경.

Revision ID: f3a9c1d4b2e6
Revises: 7980b42b0eb9
Create Date: 2026-05-24

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3a9c1d4b2e6"
down_revision: Union[str, Sequence[str], None] = "7980b42b0eb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# id 자동증가가 필요한 모든 테이블
TABLES = [
    "users",
    "trips",
    "trip_days",
    "diaries",
    "photos",
    "diary_generations",
    "photo_generations",
]


def upgrade() -> None:
    for table in TABLES:
        # id 컬럼을 자동증가(IDENTITY)로. BY DEFAULT = 직접 지정도 허용(시드 호환).
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
        )
        # 기존 데이터와 충돌 안 나게 시퀀스를 현재 max(id) 다음으로 맞춤.
        #   - 데이터 있으면: is_called=true → 다음 값 = max(id)+1
        #   - 비어 있으면:   is_called=false → 다음 값 = 1
        op.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence('{table}', 'id'),
                GREATEST((SELECT COALESCE(MAX(id), 0) FROM {table}), 1),
                (SELECT COUNT(*) > 0 FROM {table})
            )
            """
        )


def downgrade() -> None:
    for table in TABLES:
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN id DROP IDENTITY IF EXISTS"
        )
